/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/auth-data';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from 'ionic-angular/components/alert/alert';
import * as import12 from 'ionic-angular/components/loading/loading';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/platform/platform';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from 'ionic-angular/components/label/label';
import * as import42 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import43 from '@angular/forms/src/directives/ng_control';
import * as import44 from '@angular/forms/src/directives/ng_control_status';
import * as import45 from 'ionic-angular/components/input/input';
import * as import46 from 'ionic-angular/components/item/item';
import * as import47 from '@angular/common/src/directives/ng_if';
import * as import48 from 'ionic-angular/components/button/button';
import * as import49 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import50 from '@angular/forms/src/directives/control_container';
import * as import51 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthData),this.parentInjector.get(import10.FormBuilder),this.parentInjector.get(import11.AlertController),this.parentInjector.get(import12.LoadingController));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import14.ComponentFactory<import0.LoginPage> = new import14.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _el_0:any;
  _Header_0_3:import15.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import16.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import17.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import18.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _FormGroupDirective_13_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_13_4:any;
  _NgControlStatusGroup_13_5:import20.Wrapper_NgControlStatusGroup;
  _text_14:any;
  _el_15:any;
  /*private*/ _appEl_15:import3.AppElement;
  _Item_15_4:import21.Wrapper_Item;
  _ItemContent_15_5:import21.Wrapper_ItemContent;
  _query_Label_15_0:import22.QueryList<any>;
  _query_Button_15_1:import22.QueryList<any>;
  _query_Icon_15_2:import22.QueryList<any>;
  _text_16:any;
  _el_17:any;
  _Label_17_3:import23.Wrapper_Label;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _FormControlName_20_4:import24.Wrapper_FormControlName;
  _NgControl_20_5:any;
  _NgControlStatus_20_6:import20.Wrapper_NgControlStatus;
  _TextInput_20_7:import25.Wrapper_TextInput;
  _text_21:any;
  _text_22:any;
  _anchor_23:any;
  /*private*/ _appEl_23:import3.AppElement;
  _TemplateRef_23_5:any;
  _NgIf_23_6:import26.Wrapper_NgIf;
  _text_24:any;
  _el_25:any;
  /*private*/ _appEl_25:import3.AppElement;
  _Item_25_4:import21.Wrapper_Item;
  _ItemContent_25_5:import21.Wrapper_ItemContent;
  _query_Label_25_0:import22.QueryList<any>;
  _query_Button_25_1:import22.QueryList<any>;
  _query_Icon_25_2:import22.QueryList<any>;
  _text_26:any;
  _el_27:any;
  _Label_27_3:import23.Wrapper_Label;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _FormControlName_30_4:import24.Wrapper_FormControlName;
  _NgControl_30_5:any;
  _NgControlStatus_30_6:import20.Wrapper_NgControlStatus;
  _TextInput_30_7:import25.Wrapper_TextInput;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import26.Wrapper_NgIf;
  _text_34:any;
  _el_35:any;
  /*private*/ _appEl_35:import3.AppElement;
  _Button_35_4:import27.Wrapper_Button;
  _text_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  /*private*/ _appEl_39:import3.AppElement;
  _Button_39_4:import27.Wrapper_Button;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _Button_42_4:import27.Wrapper_Button;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import15.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'color','primary');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Login',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import18.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import18.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_11,'src','http://placehold.it/300x100');
    this._text_12 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_13,'novalidate','');
    this._FormGroupDirective_13_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_13_4 = this._FormGroupDirective_13_3.context;
    this._NgControlStatusGroup_13_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_13_4);
    this._text_14 = this.renderer.createText(this._el_13,'\n		',(null as any));
    this._el_15 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_15,'class','item item-block');
    this._appEl_15 = new import3.AppElement(15,13,this,this._el_15);
    var compView_15:any = import21.viewFactory_Item0(this.viewUtils,this.injector(15),this._appEl_15);
    this._Item_15_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_15),this.renderer);
    this._ItemContent_15_5 = new import21.Wrapper_ItemContent();
    this._query_Label_15_0 = new import22.QueryList<any>();
    this._query_Button_15_1 = new import22.QueryList<any>();
    this._query_Icon_15_2 = new import22.QueryList<any>();
    this._appEl_15.initComponent(this._Item_15_4.context,([] as any[]),compView_15);
    this._text_16 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_17 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_17,'stacked','');
    this._Label_17_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_17),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'Email',(null as any));
    this._text_19 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_20 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_20,'formControlName','email');
    this.renderer.setElementAttribute(this._el_20,'placeholder','Your email address');
    this.renderer.setElementAttribute(this._el_20,'type','email');
    this._appEl_20 = new import3.AppElement(20,15,this,this._el_20);
    var compView_20:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(20),this._appEl_20);
    this._FormControlName_20_4 = new import24.Wrapper_FormControlName(this._ControlContainer_13_4,(null as any),(null as any),(null as any));
    this._NgControl_20_5 = this._FormControlName_20_4.context;
    this._NgControlStatus_20_6 = new import20.Wrapper_NgControlStatus(this._NgControl_20_5);
    this._TextInput_20_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_15_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import37.Platform),new import29.ElementRef(this._el_20),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_20_5);
    this._appEl_20.initComponent(this._TextInput_20_7.context,([] as any[]),compView_20);
    compView_20.create(this._TextInput_20_7.context,([] as any[]),(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_15_0.reset([this._Label_17_3.context]);
    this._Item_15_4.context.contentLabel = this._query_Label_15_0.first;
    compView_15.create(this._Item_15_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_17]),
      ([] as any[]).concat([
        this._text_16,
        this._text_19,
        this._text_21
      ]
      ),
      ([] as any[]).concat([this._el_20]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_22 = this.renderer.createText(this._el_13,'\n		',(null as any));
    this._anchor_23 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._appEl_23 = new import3.AppElement(23,13,this,this._anchor_23);
    this._TemplateRef_23_5 = new import38.TemplateRef_(this._appEl_23,viewFactory_LoginPage1);
    this._NgIf_23_6 = new import26.Wrapper_NgIf(this._appEl_23.vcRef,this._TemplateRef_23_5);
    this._text_24 = this.renderer.createText(this._el_13,'\n		',(null as any));
    this._el_25 = this.renderer.createElement(this._el_13,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_25,'class','item item-block');
    this._appEl_25 = new import3.AppElement(25,13,this,this._el_25);
    var compView_25:any = import21.viewFactory_Item0(this.viewUtils,this.injector(25),this._appEl_25);
    this._Item_25_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_25),this.renderer);
    this._ItemContent_25_5 = new import21.Wrapper_ItemContent();
    this._query_Label_25_0 = new import22.QueryList<any>();
    this._query_Button_25_1 = new import22.QueryList<any>();
    this._query_Icon_25_2 = new import22.QueryList<any>();
    this._appEl_25.initComponent(this._Item_25_4.context,([] as any[]),compView_25);
    this._text_26 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_27,'stacked','');
    this._Label_27_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_27),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Password',(null as any));
    this._text_29 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_30 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_30,'formControlName','password');
    this.renderer.setElementAttribute(this._el_30,'placeholder','Your password');
    this.renderer.setElementAttribute(this._el_30,'type','password');
    this._appEl_30 = new import3.AppElement(30,25,this,this._el_30);
    var compView_30:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(30),this._appEl_30);
    this._FormControlName_30_4 = new import24.Wrapper_FormControlName(this._ControlContainer_13_4,(null as any),(null as any),(null as any));
    this._NgControl_30_5 = this._FormControlName_30_4.context;
    this._NgControlStatus_30_6 = new import20.Wrapper_NgControlStatus(this._NgControl_30_5);
    this._TextInput_30_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_25_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import37.Platform),new import29.ElementRef(this._el_30),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_30_5);
    this._appEl_30.initComponent(this._TextInput_30_7.context,([] as any[]),compView_30);
    compView_30.create(this._TextInput_30_7.context,([] as any[]),(null as any));
    this._text_31 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_25_0.reset([this._Label_27_3.context]);
    this._Item_25_4.context.contentLabel = this._query_Label_25_0.first;
    compView_25.create(this._Item_25_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_27]),
      ([] as any[]).concat([
        this._text_26,
        this._text_29,
        this._text_31
      ]
      ),
      ([] as any[]).concat([this._el_30]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_32 = this.renderer.createText(this._el_13,'\n		',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_13,(null as any));
    this._appEl_33 = new import3.AppElement(33,13,this,this._anchor_33);
    this._TemplateRef_33_5 = new import38.TemplateRef_(this._appEl_33,viewFactory_LoginPage2);
    this._NgIf_33_6 = new import26.Wrapper_NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_13,'\n		',(null as any));
    this._el_35 = this.renderer.createElement(this._el_13,'button',(null as any));
    this.renderer.setElementAttribute(this._el_35,'block','');
    this.renderer.setElementAttribute(this._el_35,'ion-button','');
    this.renderer.setElementAttribute(this._el_35,'type','submit');
    this._appEl_35 = new import3.AppElement(35,13,this,this._el_35);
    var compView_35:any = import27.viewFactory_Button0(this.viewUtils,this.injector(35),this._appEl_35);
    this._Button_35_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_35),this.renderer);
    this._appEl_35.initComponent(this._Button_35_4.context,([] as any[]),compView_35);
    this._text_36 = this.renderer.createText((null as any),'Login',(null as any));
    compView_35.create(this._Button_35_4.context,[([] as any[]).concat([this._text_36])],(null as any));
    this._text_37 = this.renderer.createText(this._el_13,'\n	',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_39,'block','');
    this.renderer.setElementAttribute(this._el_39,'clear','');
    this.renderer.setElementAttribute(this._el_39,'ion-button','');
    this._appEl_39 = new import3.AppElement(39,9,this,this._el_39);
    var compView_39:any = import27.viewFactory_Button0(this.viewUtils,this.injector(39),this._appEl_39);
    this._Button_39_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_39),this.renderer);
    this._appEl_39.initComponent(this._Button_39_4.context,([] as any[]),compView_39);
    this._text_40 = this.renderer.createText((null as any),'Create a new account',(null as any));
    compView_39.create(this._Button_39_4.context,[([] as any[]).concat([this._text_40])],(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_42,'block','');
    this.renderer.setElementAttribute(this._el_42,'clear','');
    this.renderer.setElementAttribute(this._el_42,'ion-button','');
    this._appEl_42 = new import3.AppElement(42,9,this,this._el_42);
    var compView_42:any = import27.viewFactory_Button0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Button_42_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_42),this.renderer);
    this._appEl_42.initComponent(this._Button_42_4.context,([] as any[]),compView_42);
    this._text_43 = this.renderer.createText((null as any),'Forgot password',(null as any));
    compView_42.create(this._Button_42_4.context,[([] as any[]).concat([this._text_43])],(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_12,
        this._el_13,
        this._text_38,
        this._el_39,
        this._text_41,
        this._el_42,
        this._text_44
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_45 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_13,'submit',this.eventHandler(this._handle_submit_13_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_13,'reset',this.eventHandler(this._handle_reset_13_1.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_20,'change',this.eventHandler(this._handle_change_20_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_30,'change',this.eventHandler(this._handle_change_30_0.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_39,'click',this.eventHandler(this._handle_click_39_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._anchor_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._text_45
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import40.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import32.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import41.Label) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Label_17_3.context; }
    if (((token === import42.FormControlName) && (20 === requestNodeIndex))) { return this._FormControlName_20_4.context; }
    if (((token === import43.NgControl) && (20 === requestNodeIndex))) { return this._NgControl_20_5; }
    if (((token === import44.NgControlStatus) && (20 === requestNodeIndex))) { return this._NgControlStatus_20_6.context; }
    if (((token === import45.TextInput) && (20 === requestNodeIndex))) { return this._TextInput_20_7.context; }
    if (((token === import46.Item) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._Item_15_4.context; }
    if (((token === import46.ItemContent) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._ItemContent_15_5.context; }
    if (((token === import38.TemplateRef) && (23 === requestNodeIndex))) { return this._TemplateRef_23_5; }
    if (((token === import47.NgIf) && (23 === requestNodeIndex))) { return this._NgIf_23_6.context; }
    if (((token === import41.Label) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._Label_27_3.context; }
    if (((token === import42.FormControlName) && (30 === requestNodeIndex))) { return this._FormControlName_30_4.context; }
    if (((token === import43.NgControl) && (30 === requestNodeIndex))) { return this._NgControl_30_5; }
    if (((token === import44.NgControlStatus) && (30 === requestNodeIndex))) { return this._NgControlStatus_30_6.context; }
    if (((token === import45.TextInput) && (30 === requestNodeIndex))) { return this._TextInput_30_7.context; }
    if (((token === import46.Item) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Item_25_4.context; }
    if (((token === import46.ItemContent) && ((25 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._ItemContent_25_5.context; }
    if (((token === import38.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import47.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import48.Button) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Button_35_4.context; }
    if (((token === import49.FormGroupDirective) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._FormGroupDirective_13_3.context; }
    if (((token === import50.ControlContainer) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._ControlContainer_13_4; }
    if (((token === import44.NgControlStatusGroup) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._NgControlStatusGroup_13_5.context; }
    if (((token === import48.Button) && ((39 <= requestNodeIndex) && (requestNodeIndex <= 40)))) { return this._Button_39_4.context; }
    if (((token === import48.Button) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Button_42_4.context; }
    if (((token === import51.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_2_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    const currVal_7:any = this.context.loginForm;
    this._FormGroupDirective_13_3.check_form(currVal_7,throwOnChange,false);
    this._FormGroupDirective_13_3.detectChangesInternal(this,this._el_13,throwOnChange);
    this._NgControlStatusGroup_13_5.detectChangesInternal(this,this._el_13,throwOnChange);
    if (this._Item_15_4.detectChangesInternal(this,this._el_15,throwOnChange)) { this._appEl_15.componentView.markAsCheckOnce(); }
    this._ItemContent_15_5.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Label_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    const currVal_16:any = 'email';
    this._FormControlName_20_4.check_name(currVal_16,throwOnChange,false);
    this._FormControlName_20_4.detectChangesInternal(this,this._el_20,throwOnChange);
    this._NgControlStatus_20_6.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_23:any = 'Your email address';
    this._TextInput_20_7.check_placeholder(currVal_23,throwOnChange,false);
    const currVal_24:any = 'email';
    this._TextInput_20_7.check_type(currVal_24,throwOnChange,false);
    this._TextInput_20_7.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_25:boolean = (!this.context.loginForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    this._NgIf_23_6.check_ngIf(currVal_25,throwOnChange,false);
    this._NgIf_23_6.detectChangesInternal(this,this._anchor_23,throwOnChange);
    if (this._Item_25_4.detectChangesInternal(this,this._el_25,throwOnChange)) { this._appEl_25.componentView.markAsCheckOnce(); }
    this._ItemContent_25_5.detectChangesInternal(this,this._el_25,throwOnChange);
    this._Label_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    const currVal_28:any = 'password';
    this._FormControlName_30_4.check_name(currVal_28,throwOnChange,false);
    this._FormControlName_30_4.detectChangesInternal(this,this._el_30,throwOnChange);
    this._NgControlStatus_30_6.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_35:any = 'Your password';
    this._TextInput_30_7.check_placeholder(currVal_35,throwOnChange,false);
    const currVal_36:any = 'password';
    this._TextInput_30_7.check_type(currVal_36,throwOnChange,false);
    this._TextInput_30_7.detectChangesInternal(this,this._el_30,throwOnChange);
    const currVal_37:boolean = (!this.context.loginForm.controls.password.valid && (this.context.passwordChanged || this.context.submitAttempt));
    this._NgIf_33_6.check_ngIf(currVal_37,throwOnChange,false);
    this._NgIf_33_6.detectChangesInternal(this,this._anchor_33,throwOnChange);
    const currVal_38:any = '';
    this._Button_35_4.check_block(currVal_38,throwOnChange,false);
    if (this._Button_35_4.detectChangesInternal(this,this._el_35,throwOnChange)) { this._appEl_35.componentView.markAsCheckOnce(); }
    const currVal_40:any = '';
    this._Button_39_4.check_clear(currVal_40,throwOnChange,false);
    const currVal_41:any = '';
    this._Button_39_4.check_block(currVal_41,throwOnChange,false);
    if (this._Button_39_4.detectChangesInternal(this,this._el_39,throwOnChange)) { this._appEl_39.componentView.markAsCheckOnce(); }
    const currVal_43:any = '';
    this._Button_42_4.check_clear(currVal_43,throwOnChange,false);
    const currVal_44:any = '';
    this._Button_42_4.check_block(currVal_44,throwOnChange,false);
    if (this._Button_42_4.detectChangesInternal(this,this._el_42,throwOnChange)) { this._appEl_42.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_15_1.dirty) {
        this._query_Button_15_1.reset(([] as any[]));
        this._Item_15_4.context._buttons = this._query_Button_15_1;
        this._query_Button_15_1.notifyOnChanges();
      }
      if (this._query_Icon_15_2.dirty) {
        this._query_Icon_15_2.reset(([] as any[]));
        this._Item_15_4.context._icons = this._query_Icon_15_2;
        this._query_Icon_15_2.notifyOnChanges();
      }
      if (this._query_Button_25_1.dirty) {
        this._query_Button_25_1.reset(([] as any[]));
        this._Item_25_4.context._buttons = this._query_Button_25_1;
        this._query_Button_25_1.notifyOnChanges();
      }
      if (this._query_Icon_25_2.dirty) {
        this._query_Icon_25_2.reset(([] as any[]));
        this._Item_25_4.context._icons = this._query_Icon_25_2;
        this._query_Icon_25_2.notifyOnChanges();
      }
      this._TextInput_20_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_15_4.context.ngAfterContentInit(); }
      this._TextInput_30_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_25_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_35_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_39_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_42_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._NgControlStatusGroup_13_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_13,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_13_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_13,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_13_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_13,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_13_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_13,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_13_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_13,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_13_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_13,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:boolean = (!this.context.loginForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_20,'invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = this._NgControlStatus_20_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_20,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_20_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_20,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_20_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_20,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_20_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_20,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_20_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_20,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_20_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_20,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_27:boolean = (!this.context.loginForm.controls.password.valid && (this.context.passwordChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_30,'invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = this._NgControlStatus_30_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_30,'ng-untouched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_30_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_30,'ng-touched',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_30_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_30,'ng-pristine',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_30_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_30,'ng-dirty',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_30_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_30,'ng-valid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_30_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_30,'ng-invalid',currVal_34);
      this._expr_34 = currVal_34;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_20_4.context.ngOnDestroy();
    this._TextInput_20_7.context.ngOnDestroy();
    this._FormControlName_30_4.context.ngOnDestroy();
    this._TextInput_30_7.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_submit_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loginUser()) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_13_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_13_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_change_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_20_7.context)) !== false);
    return (true && pd_0);
  }
  private _handle_change_30_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_30_7.context)) !== false);
    return (true && pd_0);
  }
  private _handle_click_39_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToSignup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.goToResetPassword()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}
class _View_LoginPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage1,renderType_LoginPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Please enter a valid email.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginPage1(viewUtils,parentInjector,declarationEl);
}
class _View_LoginPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage2,renderType_LoginPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Your password needs more than 6 characters.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginPage2(viewUtils,parentInjector,declarationEl);
}