/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './signup';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '../../providers/auth-data';
import * as import10 from '@angular/forms/src/form_builder';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from '@angular/core/src/metadata/view';
import * as import14 from '@angular/core/src/linker/component_factory';
import * as import15 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_group_directive.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import22 from '@angular/core/src/linker/query_list';
import * as import23 from '../../node_modules/ionic-angular/components/label/label.ngfactory';
import * as import24 from '../../node_modules/@angular/forms/src/directives/reactive_directives/form_control_name.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import26 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import27 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import28 from 'ionic-angular/config/config';
import * as import29 from '@angular/core/src/linker/element_ref';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/app/app';
import * as import32 from 'ionic-angular/components/toolbar/toolbar';
import * as import33 from 'ionic-angular/util/keyboard';
import * as import34 from '@angular/core/src/zone/ng_zone';
import * as import35 from 'ionic-angular/components/tabs/tabs';
import * as import36 from 'ionic-angular/util/form';
import * as import37 from 'ionic-angular/platform/platform';
import * as import38 from '@angular/core/src/linker/template_ref';
import * as import39 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import40 from 'ionic-angular/components/navbar/navbar';
import * as import41 from 'ionic-angular/components/label/label';
import * as import42 from '@angular/forms/src/directives/reactive_directives/form_control_name';
import * as import43 from '@angular/forms/src/directives/ng_control';
import * as import44 from '@angular/forms/src/directives/ng_control_status';
import * as import45 from 'ionic-angular/components/input/input';
import * as import46 from 'ionic-angular/components/item/item';
import * as import47 from '@angular/common/src/directives/ng_if';
import * as import48 from 'ionic-angular/components/button/button';
import * as import49 from '@angular/forms/src/directives/reactive_directives/form_group_directive';
import * as import50 from '@angular/forms/src/directives/control_container';
import * as import51 from 'ionic-angular/components/content/content';
export class Wrapper_SignupPage {
  context:import0.SignupPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.SignupPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SignupPage_Host:import2.RenderComponentType = (null as any);
class _View_SignupPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SignupPage_0_4:Wrapper_SignupPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage_Host0,renderType_SignupPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-signup',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupPage_0_4 = new Wrapper_SignupPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.AuthData),this.parentInjector.get(import10.FormBuilder),this.parentInjector.get(import11.LoadingController),this.parentInjector.get(import12.AlertController));
    this._appEl_0.initComponent(this._SignupPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SignupPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SignupPage) && (0 === requestNodeIndex))) { return this._SignupPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SignupPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SignupPage_Host === (null as any))) { (renderType_SignupPage_Host = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignupPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupPageNgFactory:import14.ComponentFactory<import0.SignupPage> = new import14.ComponentFactory<import0.SignupPage>('page-signup',viewFactory_SignupPage_Host0,import0.SignupPage);
const styles_SignupPage:any[] = ([] as any[]);
var renderType_SignupPage:import2.RenderComponentType = (null as any);
class _View_SignupPage0 extends import1.AppView<import0.SignupPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import15.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import16.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import17.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import18.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _FormGroupDirective_14_3:import19.Wrapper_FormGroupDirective;
  _ControlContainer_14_4:any;
  _NgControlStatusGroup_14_5:import20.Wrapper_NgControlStatusGroup;
  _text_15:any;
  _el_16:any;
  /*private*/ _appEl_16:import3.AppElement;
  _Item_16_4:import21.Wrapper_Item;
  _ItemContent_16_5:import21.Wrapper_ItemContent;
  _query_Label_16_0:import22.QueryList<any>;
  _query_Button_16_1:import22.QueryList<any>;
  _query_Icon_16_2:import22.QueryList<any>;
  _text_17:any;
  _el_18:any;
  _Label_18_3:import23.Wrapper_Label;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  /*private*/ _appEl_21:import3.AppElement;
  _FormControlName_21_4:import24.Wrapper_FormControlName;
  _NgControl_21_5:any;
  _NgControlStatus_21_6:import20.Wrapper_NgControlStatus;
  _TextInput_21_7:import25.Wrapper_TextInput;
  _text_22:any;
  _text_23:any;
  _anchor_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _TemplateRef_24_5:any;
  _NgIf_24_6:import26.Wrapper_NgIf;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _Item_26_4:import21.Wrapper_Item;
  _ItemContent_26_5:import21.Wrapper_ItemContent;
  _query_Label_26_0:import22.QueryList<any>;
  _query_Button_26_1:import22.QueryList<any>;
  _query_Icon_26_2:import22.QueryList<any>;
  _text_27:any;
  _el_28:any;
  _Label_28_3:import23.Wrapper_Label;
  _text_29:any;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _FormControlName_31_4:import24.Wrapper_FormControlName;
  _NgControl_31_5:any;
  _NgControlStatus_31_6:import20.Wrapper_NgControlStatus;
  _TextInput_31_7:import25.Wrapper_TextInput;
  _text_32:any;
  _text_33:any;
  _anchor_34:any;
  /*private*/ _appEl_34:import3.AppElement;
  _TemplateRef_34_5:any;
  _NgIf_34_6:import26.Wrapper_NgIf;
  _text_35:any;
  _el_36:any;
  /*private*/ _appEl_36:import3.AppElement;
  _Button_36_4:import27.Wrapper_Button;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage0,renderType_SignupPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import15.Wrapper_Header(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import30.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this.renderer.setElementAttribute(this._el_3,'color','primary');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import16.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import16.Wrapper_Navbar(this.parentInjector.get(import31.App),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import17.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import17.Wrapper_ToolbarTitle(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import32.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Create an Account',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import18.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import18.Wrapper_Content(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import31.App),this.parentInjector.get(import33.Keyboard),this.parentInjector.get(import34.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import35.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_12,'src','http://placehold.it/300x100');
    this._text_13 = this.renderer.createText((null as any),'\n	',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'form',(null as any));
    this.renderer.setElementAttribute(this._el_14,'novalidate','');
    this._FormGroupDirective_14_3 = new import19.Wrapper_FormGroupDirective((null as any),(null as any));
    this._ControlContainer_14_4 = this._FormGroupDirective_14_3.context;
    this._NgControlStatusGroup_14_5 = new import20.Wrapper_NgControlStatusGroup(this._ControlContainer_14_4);
    this._text_15 = this.renderer.createText(this._el_14,'\n		',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','item item-block');
    this._appEl_16 = new import3.AppElement(16,14,this,this._el_16);
    var compView_16:any = import21.viewFactory_Item0(this.viewUtils,this.injector(16),this._appEl_16);
    this._Item_16_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_16),this.renderer);
    this._ItemContent_16_5 = new import21.Wrapper_ItemContent();
    this._query_Label_16_0 = new import22.QueryList<any>();
    this._query_Button_16_1 = new import22.QueryList<any>();
    this._query_Icon_16_2 = new import22.QueryList<any>();
    this._appEl_16.initComponent(this._Item_16_4.context,([] as any[]),compView_16);
    this._text_17 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_18 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_18,'stacked','');
    this._Label_18_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_18),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Email',(null as any));
    this._text_20 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_21 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_21,'formControlName','email');
    this.renderer.setElementAttribute(this._el_21,'placeholder','Your email address');
    this.renderer.setElementAttribute(this._el_21,'type','email');
    this._appEl_21 = new import3.AppElement(21,16,this,this._el_21);
    var compView_21:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(21),this._appEl_21);
    this._FormControlName_21_4 = new import24.Wrapper_FormControlName(this._ControlContainer_14_4,(null as any),(null as any),(null as any));
    this._NgControl_21_5 = this._FormControlName_21_4.context;
    this._NgControlStatus_21_6 = new import20.Wrapper_NgControlStatus(this._NgControl_21_5);
    this._TextInput_21_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_16_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import37.Platform),new import29.ElementRef(this._el_21),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_21_5);
    this._appEl_21.initComponent(this._TextInput_21_7.context,([] as any[]),compView_21);
    compView_21.create(this._TextInput_21_7.context,([] as any[]),(null as any));
    this._text_22 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_16_0.reset([this._Label_18_3.context]);
    this._Item_16_4.context.contentLabel = this._query_Label_16_0.first;
    compView_16.create(this._Item_16_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_18]),
      ([] as any[]).concat([
        this._text_17,
        this._text_20,
        this._text_22
      ]
      ),
      ([] as any[]).concat([this._el_21]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_23 = this.renderer.createText(this._el_14,'\n		',(null as any));
    this._anchor_24 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_24 = new import3.AppElement(24,14,this,this._anchor_24);
    this._TemplateRef_24_5 = new import38.TemplateRef_(this._appEl_24,viewFactory_SignupPage1);
    this._NgIf_24_6 = new import26.Wrapper_NgIf(this._appEl_24.vcRef,this._TemplateRef_24_5);
    this._text_25 = this.renderer.createText(this._el_14,'\n		',(null as any));
    this._el_26 = this.renderer.createElement(this._el_14,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','item item-block');
    this._appEl_26 = new import3.AppElement(26,14,this,this._el_26);
    var compView_26:any = import21.viewFactory_Item0(this.viewUtils,this.injector(26),this._appEl_26);
    this._Item_26_4 = new import21.Wrapper_Item(this.parentInjector.get(import36.Form),this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_26),this.renderer);
    this._ItemContent_26_5 = new import21.Wrapper_ItemContent();
    this._query_Label_26_0 = new import22.QueryList<any>();
    this._query_Button_26_1 = new import22.QueryList<any>();
    this._query_Icon_26_2 = new import22.QueryList<any>();
    this._appEl_26.initComponent(this._Item_26_4.context,([] as any[]),compView_26);
    this._text_27 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'ion-label',(null as any));
    this.renderer.setElementAttribute(this._el_28,'stacked','');
    this._Label_28_3 = new import23.Wrapper_Label(this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_28),this.renderer,(null as any),'',(null as any),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Password',(null as any));
    this._text_30 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_31,'formControlName','password');
    this.renderer.setElementAttribute(this._el_31,'placeholder','Your password');
    this.renderer.setElementAttribute(this._el_31,'type','password');
    this._appEl_31 = new import3.AppElement(31,26,this,this._el_31);
    var compView_31:any = import25.viewFactory_TextInput0(this.viewUtils,this.injector(31),this._appEl_31);
    this._FormControlName_31_4 = new import24.Wrapper_FormControlName(this._ControlContainer_14_4,(null as any),(null as any),(null as any));
    this._NgControl_31_5 = this._FormControlName_31_4.context;
    this._NgControlStatus_31_6 = new import20.Wrapper_NgControlStatus(this._NgControl_31_5);
    this._TextInput_31_7 = new import25.Wrapper_TextInput(this.parentInjector.get(import28.Config),this.parentInjector.get(import36.Form),this._Item_26_4.context,this.parentInjector.get(import31.App),this.parentInjector.get(import37.Platform),new import29.ElementRef(this._el_31),this.renderer,this._Content_10_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_31_5);
    this._appEl_31.initComponent(this._TextInput_31_7.context,([] as any[]),compView_31);
    compView_31.create(this._TextInput_31_7.context,([] as any[]),(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_26_0.reset([this._Label_28_3.context]);
    this._Item_26_4.context.contentLabel = this._query_Label_26_0.first;
    compView_26.create(this._Item_26_4.context,[
      ([] as any[]),
      ([] as any[]).concat([this._el_28]),
      ([] as any[]).concat([
        this._text_27,
        this._text_30,
        this._text_32
      ]
      ),
      ([] as any[]).concat([this._el_31]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_33 = this.renderer.createText(this._el_14,'\n		',(null as any));
    this._anchor_34 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_34 = new import3.AppElement(34,14,this,this._anchor_34);
    this._TemplateRef_34_5 = new import38.TemplateRef_(this._appEl_34,viewFactory_SignupPage2);
    this._NgIf_34_6 = new import26.Wrapper_NgIf(this._appEl_34.vcRef,this._TemplateRef_34_5);
    this._text_35 = this.renderer.createText(this._el_14,'\n		',(null as any));
    this._el_36 = this.renderer.createElement(this._el_14,'button',(null as any));
    this.renderer.setElementAttribute(this._el_36,'block','');
    this.renderer.setElementAttribute(this._el_36,'ion-button','');
    this.renderer.setElementAttribute(this._el_36,'type','submit');
    this._appEl_36 = new import3.AppElement(36,14,this,this._el_36);
    var compView_36:any = import27.viewFactory_Button0(this.viewUtils,this.injector(36),this._appEl_36);
    this._Button_36_4 = new import27.Wrapper_Button((null as any),'',this.parentInjector.get(import28.Config),new import29.ElementRef(this._el_36),this.renderer);
    this._appEl_36.initComponent(this._Button_36_4.context,([] as any[]),compView_36);
    this._text_37 = this.renderer.createText((null as any),'Create an Account',(null as any));
    compView_36.create(this._Button_36_4.context,[([] as any[]).concat([this._text_37])],(null as any));
    this._text_38 = this.renderer.createText(this._el_14,'\n	',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_13,
        this._el_14,
        this._text_39
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_14,'submit',this.eventHandler(this._handle_submit_14_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_14,'reset',this.eventHandler(this._handle_reset_14_1.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_21,'change',this.eventHandler(this._handle_change_21_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_31,'change',this.eventHandler(this._handle_change_31_0.bind(this)));
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._anchor_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._anchor_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import39.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import40.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import32.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import41.Label) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Label_18_3.context; }
    if (((token === import42.FormControlName) && (21 === requestNodeIndex))) { return this._FormControlName_21_4.context; }
    if (((token === import43.NgControl) && (21 === requestNodeIndex))) { return this._NgControl_21_5; }
    if (((token === import44.NgControlStatus) && (21 === requestNodeIndex))) { return this._NgControlStatus_21_6.context; }
    if (((token === import45.TextInput) && (21 === requestNodeIndex))) { return this._TextInput_21_7.context; }
    if (((token === import46.Item) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._Item_16_4.context; }
    if (((token === import46.ItemContent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 22)))) { return this._ItemContent_16_5.context; }
    if (((token === import38.TemplateRef) && (24 === requestNodeIndex))) { return this._TemplateRef_24_5; }
    if (((token === import47.NgIf) && (24 === requestNodeIndex))) { return this._NgIf_24_6.context; }
    if (((token === import41.Label) && ((28 <= requestNodeIndex) && (requestNodeIndex <= 29)))) { return this._Label_28_3.context; }
    if (((token === import42.FormControlName) && (31 === requestNodeIndex))) { return this._FormControlName_31_4.context; }
    if (((token === import43.NgControl) && (31 === requestNodeIndex))) { return this._NgControl_31_5; }
    if (((token === import44.NgControlStatus) && (31 === requestNodeIndex))) { return this._NgControlStatus_31_6.context; }
    if (((token === import45.TextInput) && (31 === requestNodeIndex))) { return this._TextInput_31_7.context; }
    if (((token === import46.Item) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._Item_26_4.context; }
    if (((token === import46.ItemContent) && ((26 <= requestNodeIndex) && (requestNodeIndex <= 32)))) { return this._ItemContent_26_5.context; }
    if (((token === import38.TemplateRef) && (34 === requestNodeIndex))) { return this._TemplateRef_34_5; }
    if (((token === import47.NgIf) && (34 === requestNodeIndex))) { return this._NgIf_34_6.context; }
    if (((token === import48.Button) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 37)))) { return this._Button_36_4.context; }
    if (((token === import49.FormGroupDirective) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._FormGroupDirective_14_3.context; }
    if (((token === import50.ControlContainer) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._ControlContainer_14_4; }
    if (((token === import44.NgControlStatusGroup) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 38)))) { return this._NgControlStatusGroup_14_5.context; }
    if (((token === import51.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    const currVal_0:any = 'primary';
    this._Navbar_3_4.check_color(currVal_0,throwOnChange,false);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    const currVal_7:any = this.context.signupForm;
    this._FormGroupDirective_14_3.check_form(currVal_7,throwOnChange,false);
    this._FormGroupDirective_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    this._NgControlStatusGroup_14_5.detectChangesInternal(this,this._el_14,throwOnChange);
    if (this._Item_16_4.detectChangesInternal(this,this._el_16,throwOnChange)) { this._appEl_16.componentView.markAsCheckOnce(); }
    this._ItemContent_16_5.detectChangesInternal(this,this._el_16,throwOnChange);
    this._Label_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_16:any = 'email';
    this._FormControlName_21_4.check_name(currVal_16,throwOnChange,false);
    this._FormControlName_21_4.detectChangesInternal(this,this._el_21,throwOnChange);
    this._NgControlStatus_21_6.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_23:any = 'Your email address';
    this._TextInput_21_7.check_placeholder(currVal_23,throwOnChange,false);
    const currVal_24:any = 'email';
    this._TextInput_21_7.check_type(currVal_24,throwOnChange,false);
    this._TextInput_21_7.detectChangesInternal(this,this._el_21,throwOnChange);
    const currVal_25:boolean = (!this.context.signupForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    this._NgIf_24_6.check_ngIf(currVal_25,throwOnChange,false);
    this._NgIf_24_6.detectChangesInternal(this,this._anchor_24,throwOnChange);
    if (this._Item_26_4.detectChangesInternal(this,this._el_26,throwOnChange)) { this._appEl_26.componentView.markAsCheckOnce(); }
    this._ItemContent_26_5.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Label_28_3.detectChangesInternal(this,this._el_28,throwOnChange);
    const currVal_28:any = 'password';
    this._FormControlName_31_4.check_name(currVal_28,throwOnChange,false);
    this._FormControlName_31_4.detectChangesInternal(this,this._el_31,throwOnChange);
    this._NgControlStatus_31_6.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_35:any = 'Your password';
    this._TextInput_31_7.check_placeholder(currVal_35,throwOnChange,false);
    const currVal_36:any = 'password';
    this._TextInput_31_7.check_type(currVal_36,throwOnChange,false);
    this._TextInput_31_7.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_37:boolean = (!this.context.signupForm.controls.password.valid && (this.context.passwordChanged || this.context.submitAttempt));
    this._NgIf_34_6.check_ngIf(currVal_37,throwOnChange,false);
    this._NgIf_34_6.detectChangesInternal(this,this._anchor_34,throwOnChange);
    const currVal_38:any = '';
    this._Button_36_4.check_block(currVal_38,throwOnChange,false);
    if (this._Button_36_4.detectChangesInternal(this,this._el_36,throwOnChange)) { this._appEl_36.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_16_1.dirty) {
        this._query_Button_16_1.reset(([] as any[]));
        this._Item_16_4.context._buttons = this._query_Button_16_1;
        this._query_Button_16_1.notifyOnChanges();
      }
      if (this._query_Icon_16_2.dirty) {
        this._query_Icon_16_2.reset(([] as any[]));
        this._Item_16_4.context._icons = this._query_Icon_16_2;
        this._query_Icon_16_2.notifyOnChanges();
      }
      if (this._query_Button_26_1.dirty) {
        this._query_Button_26_1.reset(([] as any[]));
        this._Item_26_4.context._buttons = this._query_Button_26_1;
        this._query_Button_26_1.notifyOnChanges();
      }
      if (this._query_Icon_26_2.dirty) {
        this._query_Icon_26_2.reset(([] as any[]));
        this._Item_26_4.context._icons = this._query_Icon_26_2;
        this._query_Icon_26_2.notifyOnChanges();
      }
      this._TextInput_21_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_16_4.context.ngAfterContentInit(); }
      this._TextInput_31_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_26_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_36_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_8:any = this._NgControlStatusGroup_14_5.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_14,'ng-untouched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatusGroup_14_5.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_14,'ng-touched',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatusGroup_14_5.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_14,'ng-pristine',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatusGroup_14_5.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_14,'ng-dirty',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatusGroup_14_5.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_14,'ng-valid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this._NgControlStatusGroup_14_5.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this.renderer.setElementClass(this._el_14,'ng-invalid',currVal_13);
      this._expr_13 = currVal_13;
    }
    const currVal_15:boolean = (!this.context.signupForm.controls.email.valid && (this.context.emailChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_21,'invalid',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_17:any = this._NgControlStatus_21_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_21,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_21_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_21,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_21_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_21,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_21_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_21,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_21_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_21,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_21_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_21,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_27:boolean = (!this.context.signupForm.controls.password.valid && (this.context.passwordChanged || this.context.submitAttempt));
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_31,'invalid',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = this._NgControlStatus_31_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_31,'ng-untouched',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_31_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_31,'ng-touched',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_31:any = this._NgControlStatus_31_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_31,'ng-pristine',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_31_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_31,'ng-dirty',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_31_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_31,'ng-valid',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_31_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_31,'ng-invalid',currVal_34);
      this._expr_34 = currVal_34;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._FormControlName_21_4.context.ngOnDestroy();
    this._TextInput_21_7.context.ngOnDestroy();
    this._FormControlName_31_4.context.ngOnDestroy();
    this._TextInput_31_7.context.ngOnDestroy();
    this._Content_10_4.context.ngOnDestroy();
  }
  private _handle_submit_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signupUser()) !== false);
    const pd_1:any = ((<any>this._FormGroupDirective_14_3.context.onSubmit($event)) !== false);
    return ((true && pd_0) && pd_1);
  }
  private _handle_reset_14_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._FormGroupDirective_14_3.context.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_change_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_21_7.context)) !== false);
    return (true && pd_0);
  }
  private _handle_change_31_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.elementChanged(this._TextInput_31_7.context)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SignupPage> {
  if ((renderType_SignupPage === (null as any))) { (renderType_SignupPage = viewUtils.createRenderComponentType('',0,import13.ViewEncapsulation.None,styles_SignupPage,{})); }
  return new _View_SignupPage0(viewUtils,parentInjector,declarationEl);
}
class _View_SignupPage1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage1,renderType_SignupPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Please enter a valid email.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SignupPage1(viewUtils,parentInjector,declarationEl);
}
class _View_SignupPage2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Item_0_4:import21.Wrapper_Item;
  _ItemContent_0_5:import21.Wrapper_ItemContent;
  _query_Label_0_0:import22.QueryList<any>;
  _query_Button_0_1:import22.QueryList<any>;
  _query_Icon_0_2:import22.QueryList<any>;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage2,renderType_SignupPage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','error-message item item-block');
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_Item0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Item_0_4 = new import21.Wrapper_Item(this.parent.parentInjector.get(import36.Form),this.parent.parentInjector.get(import28.Config),new import29.ElementRef(this._el_0),this.renderer);
    this._ItemContent_0_5 = new import21.Wrapper_ItemContent();
    this._query_Label_0_0 = new import22.QueryList<any>();
    this._query_Button_0_1 = new import22.QueryList<any>();
    this._query_Icon_0_2 = new import22.QueryList<any>();
    this._appEl_0.initComponent(this._Item_0_4.context,([] as any[]),compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n			',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Your password needs more than 6 characters.',(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n		',(null as any));
    this._query_Label_0_0.reset(([] as any[]));
    this._Item_0_4.context.contentLabel = this._query_Label_0_0.first;
    compView_0.create(this._Item_0_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import46.Item) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._Item_0_4.context; }
    if (((token === import46.ItemContent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._ItemContent_0_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Item_0_4.detectChangesInternal(this,this._el_0,throwOnChange)) { this._appEl_0.componentView.markAsCheckOnce(); }
    this._ItemContent_0_5.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_0_1.dirty) {
        this._query_Button_0_1.reset(([] as any[]));
        this._Item_0_4.context._buttons = this._query_Button_0_1;
        this._query_Button_0_1.notifyOnChanges();
      }
      if (this._query_Icon_0_2.dirty) {
        this._query_Icon_0_2.reset(([] as any[]));
        this._Item_0_4.context._icons = this._query_Icon_0_2;
        this._query_Icon_0_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_0_4.context.ngAfterContentInit(); }
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SignupPage2(viewUtils,parentInjector,declarationEl);
}